# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0)),
                ('max_health', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('max_mana', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('max_experience', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Condition',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('level', models.IntegerField(default=1)),
                ('story', models.CharField(max_length=2048)),
                ('quote', models.CharField(max_length=256)),
                ('sex', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Entity',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=2048)),
                ('backstory', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'Race',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=2048)),
                ('mana_cost', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('multiplier', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('inteligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Entity')),
            ],
            options={
                'db_table': 'Character',
            },
            bases=('catalog.entity',),
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Entity')),
            ],
            options={
                'db_table': 'Npc',
            },
            bases=('catalog.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Condition'),
        ),
        migrations.AddField(
            model_name='entity',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Race'),
        ),
        migrations.AddField(
            model_name='entity',
            name='skills',
            field=models.ManyToManyField(to='catalog.Skill'),
        ),
        migrations.AddField(
            model_name='entity',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Statistics'),
        ),
        migrations.AddField(
            model_name='user',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Character'),
        ),
    ]
